name: pigo
version: '1.2.1'
summary: Pure Go face detection library
description: |
  Key features:
   - Does not require OpenCV or any 3rd party modules to be installed
   - High processing speed
   - There is no need for image preprocessing prior detection
   - There is no need for the computation of integral images, image pyramid, HOG pyramid or any other similar data structure
   - The face detection is based on pixel intensity comparison encoded in the binary file tree structure
   - Fast detection of in-plane rotated faces
   - Pupils/eyes detection
grade: stable
confinement: strict
base: core18
parts:
  pigo:
    plugin: go
    source: https://github.com/esimov/pigo.git
    go-importpath: github.com/esimov/pigo
    build-packages:
      - build-essential
apps:
  pigo:
    command: bin/pigo
    plugs:
      - home
      - x11
